# Generated by Django 5.2.9 on 2025-12-26 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('centros', models.ManyToManyField(related_name='usuarios', to='donaciones.centroacopio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('talla', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=5)),
                ('condicion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO_EXC', 'Usado (Excelente)'), ('USADO_BUENO', 'Usado (Buen estado)')], max_length=20)),
                ('foto1', models.ImageField(upload_to='prendas/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='prendas/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='prendas/')),
                ('disponible', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.centroacopio')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
