# Generated by Django 5.2.9 on 2025-12-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0002_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='validada',
            field=models.BooleanField(default=False),
        ),
    ]
