# Generated by Django 5.2.9 on 2025-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0003_prenda_validada'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroacopio',
            name='google_maps_link',
            field=models.TextField(blank=True, help_text='Pega aquí el iframe de Google Maps'),
        ),
    ]
