# Generated by Django 5.2.9 on 2025-12-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0004_centroacopio_google_maps_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroacopio',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='56989007006', max_length=20),
        ),
        migrations.AlterField(
            model_name='centroacopio',
            name='google_maps_link',
            field=models.TextField(blank=True),
        ),
    ]
