# Generated by Django 5.2.9 on 2025-12-26 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0005_centroacopio_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prenda',
            name='tipo',
            field=models.CharField(choices=[('CAMISA', 'Camisa'), ('POLERA', 'Polera'), ('PANTALON', 'Pantalón'), ('ZAPATOS', 'Zapatos'), ('CHALECO', 'Chaleco'), ('POLERON', 'Polerón'), ('ABRIGO', 'Abrigo')], max_length=20),
        ),
    ]
