# Generated by Django 5.2.9 on 2025-12-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0006_prenda_fecha_creacion_alter_prenda_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='condicion',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO_EXC', 'Usado (Excelente)'), ('USADO_BUENO', 'Usado (Buen estado)'), ('USADO_DET', 'Usado (Con detalles)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='talla',
            field=models.CharField(choices=[('S', 'Pequeño'), ('M', 'Medio'), ('L', 'Largo'), ('XL', 'Extra Largo'), ('T33-34', 'T33-34'), ('T35-36', 'T35-36'), ('T37-38', 'T37-38'), ('T39-40', 'T39-40'), ('T41-42', 'T41-42'), ('T43-44', 'T43-44')], max_length=20),
        ),
    ]
