# Generated by Django 5.2.9 on 2025-12-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0007_alter_prenda_condicion_alter_prenda_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('icono', models.CharField(help_text='Clase de Bootstrap Icon (ej: bi-star-fill)', max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='prenda',
            name='talla',
            field=models.CharField(choices=[('S', 'S - Pequeño'), ('M', 'M - Medio'), ('L', 'L - Largo'), ('XL', 'XL - Extra Largo'), ('T33-34', 'T33-34'), ('T35-36', 'T35-36'), ('T37-38', 'T37-38'), ('T39-40', 'T39-40'), ('T41-42', 'T41-42'), ('T43-44', 'T43-44')], max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='logros',
            field=models.ManyToManyField(blank=True, to='donaciones.logro'),
        ),
    ]
