# Generated by Django 5.2.9 on 2025-12-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0008_logro_alter_prenda_talla_perfil_logros'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='fecha_entrega',
            field=models.DateField(blank=True, help_text='¿Qué día aproximado llevarás la prenda al centro?', null=True),
        ),
    ]
