# Generated by Django 5.2.9 on 2025-12-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0010_resenacentro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centroacopio',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='capacidad_maxima',
            field=models.IntegerField(default=50, help_text='Máximo de prendas que puede almacenar'),
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='en_vacaciones',
            field=models.BooleanField(default=False, help_text='Marcar si el centro está cerrado temporalmente'),
        ),
    ]
